on: [push]
jobs:
  run:
    runs-on: ubuntu-20.04
    name: Benchmark
    steps:
    - uses: actions/checkout@v2
    - run: make all
      working-directory: ./grpwk20
    - run: ./test.sh $(cat conf.txt | tail -n1)
      working-directory: ./grpwk20
