on: [pull_request]
jobs:
  compare-benchmark:
    runs-on: ubuntu-20.04
    name: Compare benchmark
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all histories
    - id: run-benchmark
      run: |
        result="$(./scripts/compare-benchmark.sh ${{github.base_ref}} ${{github.head_ref}})"
        result="${result//$'\n'/\\n}"
        echo "::set-output name=result::$result"
    - uses: actions/upload-artifact@v2
      with:
        name: benchmark-results
        path: ./.artifacts
    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: '```diff\n${{ steps.run-benchmark.outputs.result }}\n```' });
